# Generated by Django 3.2.4 on 2021-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
